// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConn() {
  return window['go']['main']['App']['CheckConn']();
}

export function GetGamesList() {
  return window['go']['main']['App']['GetGamesList']();
}

export function GetPins() {
  return window['go']['main']['App']['GetPins']();
}

export function GetSwitch1Games() {
  return window['go']['main']['App']['GetSwitch1Games']();
}

export function GetSwitch2Games() {
  return window['go']['main']['App']['GetSwitch2Games']();
}

export function IsMac() {
  return window['go']['main']['App']['IsMac']();
}

export function PinGame(arg1) {
  return window['go']['main']['App']['PinGame'](arg1);
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function SetGame(arg1, arg2) {
  return window['go']['main']['App']['SetGame'](arg1, arg2);
}

export function SetGameWithImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGameWithImage'](arg1, arg2, arg3);
}

export function SwitchToConsole(arg1) {
  return window['go']['main']['App']['SwitchToConsole'](arg1);
}
